version: "3.8"
# Compose file build variables set in .env
services:
  supervisor:
    build:
      context: ./build
      args:
        IMAGE_BASE: ${IMAGE_BASE:-ghcr.io/ai-dock/jupyter-pytorch:latest-cuda}
      tags:
        - "ghcr.io/ai-dock/webui:${IMAGE_TAG:-latest-jupyter}"
        
    image: ghcr.io/ai-dock/stable-diffusion-webui:${IMAGE_TAG:-latest-jupyter}
    
    security_opt:
      # For Rclone mount
      - apparmor:unconfined
      # For AMD GPU
      #- seccomp:unconfined
    
    cap_add:
      # For Rclone mount
      - SYS_ADMIN
    
    devices:
      # For Rclone mount
      - "/dev/fuse:/dev/fuse"
      # For AMD GPU
      #- "/dev/kfd:/dev/kfd"
      #- "/dev/dri:/dev/dri"
      
    # For AMD GPU
    #group_add:
    #  - video
    #  - render
    
    volumes:
      # For Rclone mount
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./config/rclone:/etc/rclone
      # Workspace
      - ${WORKSPACE_HOST:-./workspace}:${WORKSPACE:-/workspace/}:rshared
      # Will echo to root-owned authorized_keys file;
      # Avoids changing local file owner
      - ./config/authorized_keys:/root/.ssh/authorized_keys_mount
      - ./config/provisioning/default.sh:/opt/ai-dock/bin/provisioning.sh
    
    ports:
        # SSH available on host machine port 2222 to avoid conflict. Change to suit
        - ${SSH_PORT_HOST:-2222}:${SSH_PORT:-22}
        # redirect to Cloudflare quick tunnel
        - ${REDIRECTOR_PORT_HOST}:1111
        # A1111 web interface
        - ${WEBUI_PORT_HOST:-7860}:${WEBUI_PORT:-7860}
        # Jupyter server
        - ${JUPYTER_PORT_HOST:-8888}:${JUPYTER_PORT:-8888}
        # Rclone webserver for interactive configuration
        - ${RCLONE_PORT_HOST:-53682}:53682
   
    environment:
        # Don't enclose values in quotes
        - AUTO_UPDATE=${AUTO_UPDATE:-true}
        - WEBUI_BRANCH=${WEBUI_BRANCH:-master}
        - WEBUI_FLAGS=${WEBUI_FLAGS:-}
        - WEBUI_PORT=${WEBUI_PORT:-7860}
        - DIRECT_ADDRESS=${DIRECT_ADDRESS:-127.0.0.1}
        - DIRECT_ADDRESS_GET_WAN=${DIRECT_ADDRESS_GET_WAN:-false}
        - SSH_PORT=${SSH_PORT:-22}
        - WORKSPACE=${WORKSPACE:-/workspace}
        - WORKSPACE_SYNC=${WORKSPACE_SYNC:-true}
        - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN:-}
        - CF_QUICK_TUNNELS=${CF_QUICK_TUNNELS:-true}
        - TUNNEL_TRANSPORT_PROTOCOL=${TUNNEL_TRANSPORT_PROTOCOL:-http2}
        - WEB_ENABLE_AUTH=${WEB_ENABLE_AUTH:-true}
        - WEB_USER=${WEB_USER:-user}
        - WEB_PASSWORD=${WEB_PASSWORD:-true}
        # - PROVISIONING_SCRIPT=${PROVISIONING_SCRIPT:-}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
